<?php
require('./array/TwoSum.php');
require('./array/MaxProfit.php');
require('./array/ContainsDuplicate.php');
require('./array/ProductExceptSelf.php');
require('./array/MinInRotatedSortedArray.php');
require('./array/SearchRotatedSortedArray.php');
//print_r(TwoSum::solution());
//print_r(ProductExceptSelf::solution());
print_r(SearchRotatedSortedArray::solution());
