<?php
require('./array/TwoSum.php');
require('./array/MaxProfit.php');
require('./array/ContainsDuplicate.php');
require('./array/ProductExceptSelf.php');
require('./array/MinInRotatedSortedArray.php');
require('./array/SearchRotatedSortedArray.php');
require('./array/ThreeSum.php');
require('./array/ContainerWithMostWater.php');
require('./binary/SumOfTwo.php');
require('./binary/HammingWeight.php');
require('./binary/CountBits.php');
require('./binary/MissingNumber.php');
print_r(MissingNumber::solution());
