<?php
require('./array/TwoSum.php');
require('./array/MaxProfit.php');
require('./array/ContainsDuplicate.php');
require('./array/ProductExceptSelf.php');
require('./array/MinInRotatedSortedArray.php');
require('./array/SearchRotatedSortedArray.php');
require('./array/ThreeSum.php');
require('./array/ContainerWithMostWater.php');
require('./binary/SumOfTwo.php');
//print_r(TwoSum::solution());
//print_r(ProductExceptSelf::solution());
print_r(SumOfTwo::solution());
